### ISSUE TITLE
[Bug] 0.4.0 Stacktrace starting server with no index

### ISSUE THREAD

**Issue by krugster** [pinecone-io/canopy#217]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

(canopy4.0) perrykrug@Perrys-Pinecone-MacBook:~/canopy$ canopy start
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
🚨 Note 🚨
For debugging only. To run the Canopy server in production, run the command:
gunicorn canopy_server.app:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers <num_workers>
Starting Canopy server on 0.0.0.0:8000
INFO:     Started server process [11591]
INFO:     Waiting for application startup.
2023-12-11 18:17:51,493 - MainProcess - canopy_server.app [INFO    ]:  Did not find config file. Initializing engines with default configuration
ERROR:    Traceback (most recent call last):
  File "/Users/perrykrug/canopy/canopy4.0/lib/python3.11/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/Users/perrykrug/canopy/canopy4.0/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/Users/perrykrug/canopy/canopy4.0/lib/python3.11/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/Users/perrykrug/canopy/canopy4.0/lib/python3.11/site-packages/canopy_server/app.py", line 282, in startup
    _init_engines()
  File "/Users/perrykrug/canopy/canopy4.0/lib/python3.11/site-packages/canopy_server/app.py", line 338, in _init_engines
    kb.connect()
  File "/Users/perrykrug/canopy/canopy4.0/lib/python3.11/site-packages/canopy/knowledge_base/knowledge_base.py", line 240, in connect
    self._connect_index()
  File "/Users/perrykrug/canopy/canopy4.0/lib/python3.11/site-packages/canopy/knowledge_base/knowledge_base.py", line 202, in _connect_index
    raise RuntimeError(
RuntimeError: The index canopy--canopy does not exist or was deleted. Please create it by calling knowledge_base.create_canopy_index() or running the `canopy new` command

ERROR:    Application startup failed. Exiting.

### Expected Behavior

A better error message, or option to create index

### Steps To Reproduce

Run `canopy start` after a new installation, before creating canopy index.

### Environment

```markdown
- **OS**:
- **Language version**:
- **Canopy version**:
```

**Comment by igiloh-pinecone** [comment]
This was solved by #220 , closing
